' ============================================================
' 02_F004 - MANUAL STEP - shell: Shell body
' Part: GOLDEN-1-RevA
' Generated by the MTI 2D->3D pipeline. Run inside SolidWorks:
'   Tools > Macro > New (or Alt+F11), paste this file's contents,
'   then Run. Run macros strictly in numbered order.
' SolidWorks API works in METERS: every drawing value below is
' written as  value * UNIT_FACTOR.
' ============================================================
Option Explicit

Const UNIT_FACTOR As Double = 0.0254

Dim swApp As SldWorks.SldWorks
Dim swModel As SldWorks.ModelDoc2
Dim boolstatus As Boolean

' --- Append a PASS/FAIL line to ..\logs\build_log.txt next to the macros folder ---
Sub LogResult(status As String, step As String, detail As String)
    On Error Resume Next
    Dim macroPath As String, logPath As String, f As Integer
    macroPath = swApp.GetCurrentMacroPathName
    logPath = Left$(macroPath, InStrRev(macroPath, "\")) & "..\logs\build_log.txt"
    f = FreeFile
    Open logPath For Append As #f
    Print #f, Format$(Now, "yyyy-mm-dd hh:nn:ss") & "  [" & status & "]  " & step & _
        IIf(Len(detail) > 0, "  -- " & detail, "")
    Close #f
    On Error GoTo 0
End Sub

' --- Verify a solid body exists; log and report its bounding box ---
Function VerifySolidBody(step As String) As Boolean
    Dim swPart As SldWorks.PartDoc
    Dim vBodies As Variant
    Set swPart = swModel
    vBodies = swPart.GetBodies2(swBodyType_e.swSolidBody, True)
    If IsEmpty(vBodies) Then
        VerifySolidBody = False
        LogResult "FAIL", step, "No solid body present after feature"
    Else
        ' Bounding box read from the solid body itself (IBody2::GetBodyBox) -
        ' ModelDoc2 exposes no whole-model bounding-box call in VBA.
        Dim swBody As SldWorks.Body2
        Dim vBox As Variant
        Set swBody = vBodies(0)
        vBox = swBody.GetBodyBox
        LogResult "PASS", step, "Solid body OK; bbox(drawing units) " & _
            Format$((vBox(3) - vBox(0)) / UNIT_FACTOR, "0.000") & " x " & _
            Format$((vBox(4) - vBox(1)) / UNIT_FACTOR, "0.000") & " x " & _
            Format$((vBox(5) - vBox(2)) / UNIT_FACTOR, "0.000")
        VerifySolidBody = True
    End If
End Function

' --- Append a machine-readable result line to ..\logs\macro_result.json (JSON Lines) ---
' Every feature-creation outcome is recorded here (feature name -> success/fail)
' so the web UI / FastAPI side can surface the EXACT failing feature instead of a
' generic pipeline exit code.
Sub WriteMacroResult(featureName As String, status As String, detail As String)
    On Error Resume Next
    Dim macroPath As String, p As String, f As Integer, q As String
    q = Chr$(34)
    macroPath = swApp.GetCurrentMacroPathName
    p = Left$(macroPath, InStrRev(macroPath, "\")) & "..\logs\macro_result.json"
    f = FreeFile
    Open p For Append As #f
    Print #f, "{" & q & "feature" & q & ": " & q & featureName & q & ", " & _
        q & "status" & q & ": " & q & status & q & ", " & _
        q & "detail" & q & ": " & q & Replace(Replace(detail, "\", "/"), q, "'") & q & "}"
    Close #f
    On Error GoTo 0
End Sub

' --- Create a circular pattern with the exact selection contract the API requires ---
' Signature pulled from the INSTALLED SolidWorks type library (sldworks.tlb,
' IFeatureManager::FeatureCircularPattern5, dispid 261; see the local API help
' topic "FeatureCircularPattern5 Method (IFeatureManager)"):
'   FeatureCircularPattern5(Number As Long, Spacing As Double, FlipDirection As Boolean,
'     DName As String, GeometryPattern As Boolean, EqualSpacing As Boolean,
'     VaryInstance As Boolean, SyncSubAssemblies As Boolean, BDir2 As Boolean,
'     BSymmetric As Boolean, Number2 As Long, Spacing2 As Double, DName2 As String,
'     EqualSpacing2 As Boolean)
' Conventions asserted ONCE here, never re-interpreted downstream:
'   * Number (totalInstances) INCLUDES the seed: 6 = seed + 5 copies.
'   * Spacing is the TOTAL angle in RADIANS when EqualSpacing=True.
' Selection contract (a wrong/missing mark = silent Nothing return):
'   pattern axis  -> SelectByID2 ... Mark:=1
'   seed feature  -> SelectByID2 ... Mark:=4 (type "BODYFEATURE", exact tree name)
Function CreateCircularPatternSafe(axisName As String, seedName As String, _
        totalInstances As Integer, totalAngleDeg As Double, reverseDir As Boolean, _
        geometryPattern As Boolean, varySketch As Boolean, newName As String, _
        stepName As String) As Boolean
    Dim swFeat As SldWorks.Feature
    Dim spacingRad As Double
    spacingRad = totalAngleDeg * 4# * Atn(1#) / 180#
    swModel.ClearSelection2 True
    If Not swModel.Extension.SelectByID2(axisName, "AXIS", 0, 0, 0, False, 1, Nothing, 0) Then
        LogResult "FAIL", stepName, "Could not select pattern axis '" & axisName & "' (Mark=1)"
        Exit Function
    End If
    If Not swModel.Extension.SelectByID2(seedName, "BODYFEATURE", 0, 0, 0, True, 4, Nothing, 0) Then
        LogResult "FAIL", stepName, "Could not select seed feature '" & seedName & "' (Mark=4)"
        Exit Function
    End If
    On Error Resume Next
    Set swFeat = swModel.FeatureManager.FeatureCircularPattern5( _
        totalInstances, spacingRad, reverseDir, "NULL", geometryPattern, True, varySketch, _
        False, False, False, 1, spacingRad, "NULL", False)
    On Error GoTo 0
    If swFeat Is Nothing Then
        ' Older-release fallback: FeatureCircularPattern4 (same leading 7 arguments).
        On Error Resume Next
        Set swFeat = swModel.FeatureManager.FeatureCircularPattern4( _
            totalInstances, spacingRad, reverseDir, "NULL", geometryPattern, True, varySketch)
        On Error GoTo 0
    End If
    If swFeat Is Nothing Then Exit Function
    ' Name the pattern feature immediately so downstream selections never depend
    ' on SolidWorks' auto-numbering (CirPattern1 vs CirPattern2 drift).
    swFeat.Name = newName
    CreateCircularPatternSafe = True
End Function

' --- Select a reference plane robustly (plane names vary by template / language) ---
Function SelectRefPlane(planeName As String, planeIndex As Integer) As Boolean
    Dim tries As Variant, i As Integer
    swModel.ClearSelection2 True
    tries = Array(planeName, Replace(planeName, " Plane", ""), "Plane" & planeIndex)
    For i = LBound(tries) To UBound(tries)
        If swModel.Extension.SelectByID2(CStr(tries(i)), "PLANE", 0, 0, 0, False, 0, Nothing, 0) Then
            SelectRefPlane = True
            Exit Function
        End If
    Next i
    ' Fallback: planeIndex-th reference plane in the feature tree (template order).
    Dim feat As SldWorks.Feature, n As Integer
    Set feat = swModel.FirstFeature
    Do While Not feat Is Nothing
        If feat.GetTypeName2 = "RefPlane" Then
            n = n + 1
            If n = planeIndex Then
                swModel.ClearSelection2 True
                SelectRefPlane = feat.Select2(False, 0)
                Exit Function
            End If
        End If
        Set feat = feat.GetNextFeature
    Loop
    SelectRefPlane = False
End Function

Sub main()
    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    If swModel Is Nothing Then
        MsgBox "No active document. Run 00_setup.vba first.", vbCritical
        LogResult "FAIL", "02_F004 - MANUAL STEP - shell: Shell body", "No active document"
        End
    End If
    ' ============ MANUAL STEP - NO GEOMETRY IS CREATED HERE ============
    ' Feature F004 (shell) cannot be scripted reliably.
    ' Build it by hand in SolidWorks using the drawing and these values:
    '   height = 0.5 (drawing units)
    ' Description: Shell body
    ' When done, re-run this macro so the build log records the step.
    MsgBox "MANUAL STEP 02_F004: build feature F004 (shell) by hand." & vbCrLf & _
        "Shell body" & vbCrLf & "See this macro's comments for the extracted values.", _
        vbExclamation, "Manual step required - F004"
    LogResult "WARN", "02_F004", "F004 (shell) requires MANUAL modeling - no geometry created"
End Sub
