' ============================================================
' 02_F003 - hole: Four 13/32 through holes at corners for mounting
' Part: 115 C-RevB
' Generated by the MTI 2D->3D pipeline. Run inside SolidWorks:
'   Tools > Macro > New (or Alt+F11), paste this file's contents,
'   then Run. Run macros strictly in numbered order.
' SolidWorks API works in METERS: every drawing value below is
' written as  value * UNIT_FACTOR.
' ============================================================
Option Explicit

Const UNIT_FACTOR As Double = 0.0254

Dim swApp As SldWorks.SldWorks
Dim swModel As SldWorks.ModelDoc2
Dim boolstatus As Boolean

' --- Append a PASS/FAIL line to ..\logs\build_log.txt next to the macros folder ---
Sub LogResult(status As String, step As String, detail As String)
    On Error Resume Next
    Dim macroPath As String, logPath As String, f As Integer
    macroPath = swApp.GetCurrentMacroPathName
    logPath = Left$(macroPath, InStrRev(macroPath, "\")) & "..\logs\build_log.txt"
    f = FreeFile
    Open logPath For Append As #f
    Print #f, Format$(Now, "yyyy-mm-dd hh:nn:ss") & "  [" & status & "]  " & step & _
        IIf(Len(detail) > 0, "  -- " & detail, "")
    Close #f
    On Error GoTo 0
End Sub

' --- Verify a solid body exists; log and report its bounding box ---
Function VerifySolidBody(step As String) As Boolean
    Dim swPart As SldWorks.PartDoc
    Dim vBodies As Variant
    Set swPart = swModel
    vBodies = swPart.GetBodies2(swBodyType_e.swSolidBody, True)
    If IsEmpty(vBodies) Then
        VerifySolidBody = False
        LogResult "FAIL", step, "No solid body present after feature"
    Else
        ' Bounding box read from the solid body itself (IBody2::GetBodyBox) -
        ' ModelDoc2 exposes no whole-model bounding-box call in VBA.
        Dim swBody As SldWorks.Body2
        Dim vBox As Variant
        Set swBody = vBodies(0)
        vBox = swBody.GetBodyBox
        LogResult "PASS", step, "Solid body OK; bbox(drawing units) " & _
            Format$((vBox(3) - vBox(0)) / UNIT_FACTOR, "0.000") & " x " & _
            Format$((vBox(4) - vBox(1)) / UNIT_FACTOR, "0.000") & " x " & _
            Format$((vBox(5) - vBox(2)) / UNIT_FACTOR, "0.000")
        VerifySolidBody = True
    End If
End Function

' --- Select a reference plane robustly (plane names vary by template / language) ---
Function SelectRefPlane(planeName As String, planeIndex As Integer) As Boolean
    Dim tries As Variant, i As Integer
    swModel.ClearSelection2 True
    tries = Array(planeName, Replace(planeName, " Plane", ""), "Plane" & planeIndex)
    For i = LBound(tries) To UBound(tries)
        If swModel.Extension.SelectByID2(CStr(tries(i)), "PLANE", 0, 0, 0, False, 0, Nothing, 0) Then
            SelectRefPlane = True
            Exit Function
        End If
    Next i
    ' Fallback: planeIndex-th reference plane in the feature tree (template order).
    Dim feat As SldWorks.Feature, n As Integer
    Set feat = swModel.FirstFeature
    Do While Not feat Is Nothing
        If feat.GetTypeName2 = "RefPlane" Then
            n = n + 1
            If n = planeIndex Then
                swModel.ClearSelection2 True
                SelectRefPlane = feat.Select2(False, 0)
                Exit Function
            End If
        End If
        Set feat = feat.GetNextFeature
    Loop
    SelectRefPlane = False
End Function

Sub main()
    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    If swModel Is Nothing Then
        MsgBox "No active document. Run 00_setup.vba first.", vbCritical
        LogResult "FAIL", "02_F003 - hole: Four 13/32 through holes at corners for mounting", "No active document"
        End
    End If
    ' ---- PLANE SELECTION (Top Plane; name auto-detected) ----
    If Not SelectRefPlane("Top Plane", 2) Then
        MsgBox "Could not select Top Plane (no reference plane found).", vbCritical
        LogResult "FAIL", "02_F003", "Could not select Top Plane (no reference plane found)."
        End
    End If

    ' ---- OPEN SKETCH ----
    swModel.SketchManager.InsertSketch True
    ' ---- SKETCH: 1 hole(s) dia 0.40625 (thru) ----
    swModel.SketchManager.CreateCircleByRadius 1.625 * UNIT_FACTOR, 1.375 * UNIT_FACTOR, 0#, (0.40625 / 2#) * UNIT_FACTOR
    ' NOTE: HOLE POSITIONS ASSUMED (centered on the plate envelope) - verify against the drawing.

    ' ---- FINALIZE SKETCH ----
    ' The feature call below consumes the ACTIVE sketch - this is exactly what
    ' SolidWorks' own macro recorder emits (ClearSelection2 then the feature
    ' call, sketch left open). No closing, no name-based reselection.
    On Error Resume Next
    swModel.SketchManager.FullyDefineSketch True, True, 0, True, 1, Nothing, 1, Nothing, 0, 0
    On Error GoTo 0
    swModel.ClearSelection2 True
    If swModel.SketchManager.ActiveSketch Is Nothing Then
        MsgBox "No active sketch to build the feature from.", vbCritical
        LogResult "FAIL", "02_F003", "No active sketch to build the feature from."
        End
    End If

    ' ---- CUT ----
    Dim swFeat As SldWorks.Feature
    Set swFeat = swModel.FeatureManager.FeatureCut4( _
        True, False, False, _
        swEndConditions_e.swEndCondThroughAllBoth, swEndConditions_e.swEndCondBlind, _
        0#, 0.01, _
        False, False, False, False, 0#, 0#, _
        False, False, False, False, False, _
        True, True, True, True, False, _
        swStartConditions_e.swStartSketchPlane, 0#, False, False)
    If swFeat Is Nothing Then
        ' The cut may have missed the material (body on the other side of the
        ' sketch plane) - restore the profile sketch and retry, direction flipped.
        If swModel.SketchManager.ActiveSketch Is Nothing Then
            ' Sketch was consumed/closed by the failed attempt: select the most
            ' recent sketch feature in the tree (type "ProfileFeature") by object,
            ' never by name.
            Dim featRswFeat As SldWorks.Feature, lastSkswFeat As SldWorks.Feature
            Set featRswFeat = swModel.FirstFeature
            Do While Not featRswFeat Is Nothing
                If featRswFeat.GetTypeName2 = "ProfileFeature" Then Set lastSkswFeat = featRswFeat
                Set featRswFeat = featRswFeat.GetNextFeature
            Loop
            swModel.ClearSelection2 True
            If Not lastSkswFeat Is Nothing Then lastSkswFeat.Select2 False, 0
        End If
        Set swFeat = swModel.FeatureManager.FeatureCut4( _
            True, False, True, _
            swEndConditions_e.swEndCondThroughAll, swEndConditions_e.swEndCondBlind, _
            0#, 0.01, _
            False, False, False, False, 0#, 0#, _
            False, False, False, False, False, _
            True, True, True, True, False, _
            swStartConditions_e.swStartSketchPlane, 0#, False, False)
    End If

    If swFeat Is Nothing Then
        MsgBox "Feature creation returned Nothing - check the sketch.", vbCritical
        LogResult "FAIL", "02_F003", "Feature creation returned Nothing - check the sketch."
        End
    End If
    swFeat.Name = "F003_Four_13_32_through_holes_at_corners_for_"
    If Not VerifySolidBody("02_F003") Then
        MsgBox "No solid body after this feature.", vbCritical
        LogResult "FAIL", "02_F003", "No solid body after this feature."
        End
    End If
    LogResult "PASS", "02_F003", "Created feature F003_Four_13_32_through_holes_at_corners_for_"
End Sub
